sudo: required
dist: trusty
services:
  - docker
os:
- linux
- osx
language: cpp

before_install:
  - git fetch --tags && git fetch
  - ./scripts/ci/$TRAVIS_OS_NAME/before_install.sh

install:
  - ./scripts/ci/$TRAVIS_OS_NAME/install.sh

script:
  - ./scripts/ci/$TRAVIS_OS_NAME/script.sh

after_success:
  - ./scripts/ci/$TRAVIS_OS_NAME/after_success.sh

branches:
  only:
  - "/^v.*$/"
  - master
env:
  global:
    secure: h23MwFRN5UwPGAL+6cnl+lDsfDXYFkoLunLKUROviJh7M7wioP25lswMKZmv/rumPDjNtusvfbYcRr42YRM58O6On60xBs3MraYeio5oU7bjOvBjLbEXsgL56TtXxpcYjoO8MnRAknYU2iV9aHyMLDU9DAvp6Wq6KsW0vLn0cRQ=
